website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, Flask, session, send_file
from flask_sqlalchemy import SQLAlchemy
from flask_login import login_required, current_user
from .models import Users, Events, Packages, UserRequests
from . import db
import json, os, threading
from datetime import datetime, date, timedelta
from sqlalchemy import and_, func, cast, String, text, desc, case, literal_column
from PIL import Image
from io import BytesIO
import shutil

views =  Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    try:
        result_data = Events.query.order_by(Events.ev_date.desc()).all()
    except Exception as e:
        print(f"Error: {e}")
    return render_template("index.html", user=current_user, result=result_data)

@views.route('/userInfo/<int:user_id>', methods=['GET', 'POST'])
@login_required
def userInfo(p_user_id):
    pass_user = Users.query.get_or_404(p_user_id)
    return render_template("user_info.html", user=current_user, p_user=pass_user)

@views.route('/userOwnInfo', methods=['GET', 'POST'])
@login_required
def userOwnInfo():
    return render_template("user_own_info.html", user=current_user)

# management
@views.route('/managementEvents', methods=['GET', 'POST'])
@login_required
def managementEvents():
    result_data = Events.query.filter_by(ev_user_id=current_user.us_id).order_by(Events.ev_date.desc()).all()
    return render_template("managementEvents.html", user=current_user, result=result_data)

@views.route('/managementUsersSU', methods=['GET', 'POST'])
@login_required
def managementUsersSU():
    result_data = Users.query.order_by(Users.us_id.desc()).all()
    return render_template("managementUsersSU.html", user=current_user, result=result_data)

@views.route('/managementUsersAdmin', methods=['GET', 'POST'])
@login_required
def managementUsersAdmin():
    result_data = Users.query.filter(Users.us_is_admin == 0, Users.us_is_superuser == 0).order_by(Users.us_id.desc()).all()
    return render_template("managementUsersAdmin.html", user=current_user, result=result_data)

# current user management
@views.route('/updateOwnUser', methods=['GET', 'POST'])
@login_required
def updateOwnUser():
    user_id = current_user.us_id
    user_Name = request.form.get('user_name')
    user_Email = request.form.get('user_email')
    user_birthday = request.form.get('user_birthday')
    
    if request.form.get('user_active') == 'on':
        user_is_active = 1
    else:
        user_is_active = 0

    if request.form.get('user_buyer') == 'on':
        user_is_buyer = 1
    else:
        user_is_buyer = 0

    if request.form.get('user_seller') == 'on':
        user_is_seller = 1
    else:
        user_is_seller = 0

    if request.form.get('user_admin') == 'on':
        user_is_admin = 1
    else:
        user_is_admin = 0

    if request.form.get('user_superuser') == 'on':
        user_is_superuser = 1
    else:
        user_is_superuser = 0
    # user_Photo = request.form.get('user_photo')
    
    # Update User
    try:
        db.session.execute(
        text(f"UPDATE tb_users SET us_name=:user_Name, us_email=:user_Email, us_birthday=:user_birthday, us_is_active=:user_is_active, us_is_buyer=:user_is_buyer, us_is_seller=:user_is_seller, us_is_admin=:user_is_admin, us_is_superuser=:user_is_superuser WHERE us_id=:user_id"),
            {"user_Name": user_Name, "user_Email": user_Email, "user_id": user_id, "user_birthday": user_birthday, "user_is_active": user_is_active, "user_is_buyer": user_is_buyer, "user_is_seller": user_is_seller, "user_is_admin": user_is_admin, "user_is_superuser": user_is_superuser}
        )
        db.session.commit()
    except Exception as e:
        print("Error: " + str(e))

    # Insert photo of user
    image = request.files['user_photo']
    if image and user_id>0:
        #image is found")
        # path = 'website/static/photos/users/'+str(user_id)+'/'
        path = str(os.path.abspath(os.path.dirname(__file__)))+'/static/photos/users/'+str(user_id)+'/'
        pathRelative = 'static\\photos\\users\\'+str(user_id)+'\\'
        filePath = str(os.path.abspath(os.path.dirname(__file__)))+'/static/photos/users/'+str(user_id)+'/main.jpg'
                
        # Check if directory exists, if not, create it.
        if os.path.exists(path) == False:
            #print('Dir path not found')
            os.mkdir(path)
        # Check if main.jpg exists, if exists delete it
        if os.path.exists(filePath) == True:
            os.remove(filePath)
        
        # Upload image to directory
        fileName = 'main.jpg'
        basedir = os.path.abspath(os.path.dirname(__file__))
        #print(f"basedir: {basedir}")
        #print(f"filePath: {filePath}")
        newPath = os.path.join(basedir, pathRelative, fileName)
        # image.save(newPath)
        image.save(filePath)
        #print("image saved")


    return render_template("user_own_info.html", user=current_user)


# user management by id
@views.route('/updateUser/<int:userID>', methods=['GET', 'POST'])
@login_required
def updateUser(userID):
    user_id = userID
    pass_user = Users.query.get_or_404(userID)
    user_Name = request.form.get('user_name')
    user_Email = request.form.get('user_email')
    user_birthday = request.form.get('user_birthday')
    
    if request.form.get('user_active') == 'on':
        user_is_active = 1
    else:
        user_is_active = 0

    if request.form.get('user_buyer') == 'on':
        user_is_buyer = 1
    else:
        user_is_buyer = 0

    if request.form.get('user_seller') == 'on':
        user_is_seller = 1
    else:
        user_is_seller = 0

    if request.form.get('user_admin') == 'on':
        user_is_admin = 1
    else:
        user_is_admin = 0

    if request.form.get('user_superuser') == 'on':
        user_is_superuser = 1
    else:
        user_is_superuser = 0
    # Update User
    try:
        db.session.execute(
        text(f"UPDATE tb_users SET us_name=:user_Name, us_email=:user_Email, us_birthday=:user_birthday, us_is_active=:user_is_active, us_is_buyer=:user_is_buyer, us_is_seller=:user_is_seller, us_is_admin=:user_is_admin, us_is_superuser=:user_is_superuser WHERE us_id=:user_id"),
            {"user_Name": user_Name, "user_Email": user_Email, "user_id": user_id, "user_birthday": user_birthday, "user_is_active": user_is_active, "user_is_buyer": user_is_buyer, "user_is_seller": user_is_seller, "user_is_admin": user_is_admin, "user_is_superuser": user_is_superuser}
        )
        db.session.commit()
    except Exception as e:
        print("Error: " + str(e))

    # Insert photo of user
    image = request.files['user_photo']
    if image and user_id>0:
        #image is found")
        # path = 'website/static/photos/users/'+str(user_id)+'/'
        path = str(os.path.abspath(os.path.dirname(__file__)))+'/static/photos/users/'+str(user_id)+'/'
        pathRelative = 'static\\photos\\users\\'+str(user_id)+'\\'
        filePath = str(os.path.abspath(os.path.dirname(__file__)))+'/static/photos/users/'+str(user_id)+'/main.jpg'
                
        # Check if directory exists, if not, create it.
        if os.path.exists(path) == False:
            #print('Dir path not found')
            os.mkdir(path)
        # Check if main.jpg exists, if exists delete it
        if os.path.exists(filePath) == True:
            os.remove(filePath)
        
        # Upload image to directory
        fileName = 'main.jpg'
        basedir = os.path.abspath(os.path.dirname(__file__))
        #print(f"basedir: {basedir}")
        #print(f"filePath: {filePath}")
        newPath = os.path.join(basedir, pathRelative, fileName)
        # image.save(newPath)
        image.save(filePath)
        #print("image saved")


    # return render_template("user_info.html", user=current_user, p_user=pass_user)
    return redirect(url_for('views.managementUsersSU'))


@views.route('/saveUserChanges', methods=['POST'])
@login_required
def saveUserChanges():
    for user in Users.query.all():
        user.us_is_buyer = 'us_is_buyer_' + str(user.us_id) in request.form
        user.us_is_seller = 'us_is_seller_' + str(user.us_id) in request.form
        user.us_is_admin = 'us_is_admin_' + str(user.us_id) in request.form
        user.us_is_active = 'us_is_active_' + str(user.us_id) in request.form
        user.us_is_superuser = 'us_is_superuser_' + str(user.us_id) in request.form
    db.session.commit()
    return redirect(url_for('views.managementUsersSU'))

@views.route('/editUser/<int:user_id>', methods=['GET', 'POST'])
@login_required
def editUser(user_id):
    p_user = Users.query.get_or_404(user_id)
    
    return render_template('user_info.html', user=current_user, p_user=p_user)

#tools
def crop_image_in_memory(filePath):
    img = Image.open(filePath)
    width, height = img.size
    min_dim = min(width, height)
    left = (width - min_dim) / 2
    top = (height - min_dim) / 2
    right = (width + min_dim) / 2
    bottom = (height + min_dim) / 2
    img = img.crop((left, top, right, bottom))
    return img

@views.route('/display_user_image/<userID>')
def display_user_image(userID):
    filePath = str(os.path.abspath(os.path.dirname(__file__)))+'/static/photos/users/'+str(userID)+'/main.jpg'
    if os.path.isfile(filePath):
        img = crop_image_in_memory(filePath)
        img_io = BytesIO()
        img.save(img_io, 'JPEG')
        img_io.seek(0)
        return send_file(img_io, mimetype='image/jpeg')
    else:
        return redirect(url_for('static', filename='photos/users/nophoto.jpg'), code=301)

@views.route('/display_event_main_image/<eventID>')
def display_event_main_image(eventID):
    filePath = str(os.path.abspath(os.path.dirname(__file__)))+'/static/photos/01_events/'+str(eventID)+'/main.jpg'
    if os.path.isfile(filePath):
        img = crop_image_in_memory(filePath)
        img_io = BytesIO()
        img.save(img_io, 'JPEG')
        img_io.seek(0)

website/templates/create_event.html
{% extends 'base.html' %}
{% block content %}
<form action="{{ url_for('views.create_event') }}" method="post" enctype="multipart/form-data">
    <div class="col-md-12">
        <!-- Full data -->
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ translate('Create Event') }}</h5>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="title">{{ translate('Title') }}</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="text" class="form-control form-control-rounded" id="title" placeholder="{{ translate('Title of Event') }}" name="title" value="">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="description">{{ translate('Description') }}</label>
                    </div>
                    <div class="col-sm-9">
                        <textarea class="form-control form-control-rounded" id="description" placeholder="{{ translate('Description of Event') }}" name="description" rows="5"></textarea>
                    </div>
                </div>  
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="location">{{ translate('Location') }}</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="text" class="form-control form-control-rounded" id="location" placeholder="{{ translate('Place of Event') }}" name="location" value="">
                    </div>
                </div> 
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="ev_date">{{ translate('Event Date') }}</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="date" class="form-control form-control-rounded" id="ev_date" name="ev_date" value="">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="ev_expected_attendance">{{ translate('Expected Attendance') }}</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="number" class="form-control form-control-rounded" id="ev_expected_attendance" placeholder="{{ translate('Expected Attendance') }}" name="ev_expected_attendance" value="">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="ev_instagram">Instagram</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="text" class="form-control form-control-rounded" id="ev_instagram" placeholder="Instagram Link" name="ev_instagram" value="">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="ev_facebook">Facebook</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="text" class="form-control form-control-rounded" id="ev_facebook" placeholder="Facebook Link" name="ev_facebook" value="">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="ev_youtube">YouTube</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="text" class="form-control form-control-rounded" id="ev_youtube" placeholder="YouTube Link" name="ev_youtube" value="">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="ev_tiktok">TikTok</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="text" class="form-control form-control-rounded" id="ev_tiktok" placeholder="TikTok Link" name="ev_tiktok" value="">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="ev_main_photo">{{ translate('Main Event Photo') }}</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="file" class="form-control form-control-rounded" id="ev_main_photo" name="ev_main_photo" accept="image/*">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="ev_secondary_photos">{{ translate('Secondary Event Photos') }}</label>
                    </div>
                    <div class="col-sm-9">
                        <input type="file" class="form-control form-control-rounded" id="ev_secondary_photos" name="ev_secondary_photos" multiple accept="image/*">
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <button type="submit" class="btn btn-light btn-round px-5"><i class="icon-save"></i> {{ translate('Create Event') }}</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

website/templates/index.html
{% extends "base.html" %} {% block title %}{{ config.TITLE }}{% endblock %} 
{% block content %}

<!-- testing -->
<div class="row">
    <h5 class="card-title">{{ translate('Events') }}</h5>    
</div>
<!-- end testing -->


<div class="row justify-content-center">
    {% for event in result %}
    <div class="col-10 col-sm-5 col-md-4 col-lg-3">
      <a href="{{ url_for('views.detail_event', event_id=event.ev_id) }}" class="card profile-card-2">
        <div class="card-img-block">
          <img class="img-fluid" src="{{ url_for('views.display_event_second_image', eventID=event.ev_id ) }}" alt="Card image cap">
        </div>
        <div class="card-body pt-5">
          <img src="{{ url_for('views.display_event_main_image', eventID=event.ev_id ) }}" alt="profile-image" class="profile">
          <h5 class="card-title">{{ event.ev_title }}</h5>
          <h6 class="card-subtitle">{{ event.ev_location }}</h6>
          <p></p>
          <p class="card-text">{{ translate('Date') }}: {{ event.ev_date.strftime('%Y-%m-%d') if event.ev_date else 'N/A' }}</p>
          <p class="card-text">{{ translate('Attendance') }}: {{ event.ev_expected_attendance }}</p>
          <!-- <p class="card-text">{{ event.ev_sold_package_count }} / {{ event.ev_package_count }}</p> -->
          <!-- <div class="icon-block">
            <a href="javascript:void();"><i class="fa fa-facebook bg-facebook text-white"></i></a>
            <a href="javascript:void();"> <i class="fa fa-twitter bg-twitter text-white"></i></a>
            <a href="javascript:void();"> <i class="fa fa-google-plus bg-google-plus text-white"></i></a>
          </div> -->
        </div>
      </a>
    </div>
    {% endfor %} 
  </div>


{% endblock %}

website/templates/managementEvents.html
{% extends "base.html" %} {% block title %}{{ config.TITLE }}{% endblock %} 
{% block content %}


<!-- testing -->
<div class="row">
    <h5 class="card-title">{{ translate('Management Events') }}</h5>
</div>
<div class="row">
    {% if user.us_is_seller %}
    <a href="{{ url_for('views.create_event') }}" class="btn btn-primary">{{ translate('Create Event') }}</a>
    {% endif %}
</div>
<br>
<!-- end testing -->



<!-- show events -->
<div class="row justify-content-center">
    {% for event in result %}
    <div class="col-10 col-sm-5 col-md-4 col-lg-3">
    <a href="{% if user.us_id == event.ev_user_id %}{{ url_for('views.edit_event', event_id=event.ev_id) }}{% else %}# {% endif %}" class="card profile-card-2">
        <div class="card-img-block">
            <img class="img-fluid" src="{{ url_for('views.display_event_main_image', eventID=event.ev_id ) }}" alt="Card image cap">
        </div>
        <div class="card-body pt-5">
            <img src="{{ url_for('views.display_user_image', userID=event.ev_user_id ) }}" alt="profile-image" class="profile">
            <h5 class="card-title">{{ event.ev_title }}</h5>
            <h6 class="card-subtitle">{{ event.ev_location }}</h6>
            <p></p>
            <p class="card-text">{{ translate('Date') }}: {{ event.ev_date.strftime('%Y-%m-%d') if event.ev_date else 'N/A' }}</p>
            <p class="card-text">{{ translate('Attendance') }}: {{ event.ev_expected_attendance }}</p>
        </div>
    </a>
    </div>
    {% endfor %} 
</div>

{% endblock %}

website/templates/managementUsersSU.html
{% extends "base.html" %} {% block title %}{{ config.TITLE }}{% endblock %} 
{% block content %}

<div class="row">
    <h5 class="card-title">{{ translate('Management User as SuperUser') }}</h5>    
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ translate('Users') }}</h5>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">{{ translate('Name') }}</th>
                                <th scope="col">{{ translate('Active') }}</th>
                                <th scope="col">{{ translate('Buyer') }}</th>
                                <th scope="col">{{ translate('Seller') }}</th>
                                <th scope="col">{{ translate('Admin') }}</th>
                                <th scope="col">{{ translate('SuperUser') }}</th>
                                <!-- <th scope="col">{{ translate('Age') }}</th> -->
                            </tr>
                        </thead>
                        <tbody>
                            {% for r_user in result %}
                            <tr>
                                <td onclick="window.location.href='{{ url_for('views.editUser', user_id=r_user.us_id) }}';">
                                    <img src="{{ url_for('views.display_user_image', userID=r_user.us_id ) }}" 
                                        alt="{{ r_user.us_name }}" class="rounded-circle" width="40">    
                                    {{ display_short_name(r_user.us_name) }}
                                </td>
                                <td onclick="window.location.href='{{ url_for('views.editUser', user_id=r_user.us_id) }}';">{% if r_user.us_is_active %}<i class="zmdi zmdi-check-square"></i>{% else %}<i class="zmdi zmdi-square-o"></i>{% endif %}</td>
                                <td onclick="window.location.href='{{ url_for('views.editUser', user_id=r_user.us_id) }}';">{% if r_user.us_is_buyer %}<i class="zmdi zmdi-check-square"></i>{% else %}<i class="zmdi zmdi-square-o"></i>{% endif %}</td>
                                <td onclick="window.location.href='{{ url_for('views.editUser', user_id=r_user.us_id) }}';">{% if r_user.us_is_seller %}<i class="zmdi zmdi-check-square"></i>{% else %}<i class="zmdi zmdi-square-o"></i>{% endif %}</td>
                                <td onclick="window.location.href='{{ url_for('views.editUser', user_id=r_user.us_id) }}';">{% if r_user.us_is_admin %}<i class="zmdi zmdi-check-square"></i>{% else %}<i class="zmdi zmdi-square-o"></i>{% endif %}</td>
                                <td onclick="window.location.href='{{ url_for('views.editUser', user_id=r_user.us_id) }}';">{% if r_user.us_is_superuser %}<i class="zmdi zmdi-check-square"></i>{% else %}<i class="zmdi zmdi-square-o"></i>{% endif %}</td>
                                <!-- <td onclick="window.location.href='{{ url_for('views.editUser', user_id=r_user.us_id) }}';">{{ calculate_age(r_user.us_birthday) }}</td> -->
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

website/templates/user_own_info.html
{% extends "base.html" %} {% block title %}{{ config.TITLE }}{% endblock %} 
{% block content %}
<!-- Show every detail of a user Row -->

<form action="{{ url_for('views.updateOwnUser') }}" method="post" enctype="multipart/form-data">
    <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
            <!-- General data -->
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <img src="{{ url_for('views.display_user_image', userID=user.us_id ) }}" alt="{{ user.us_name }}" class="rounded-circle" width="150" id="user_photo_img" style="cursor: pointer;">
                        <input type="file" class="form-control form-control-rounded" id="user_photo" placeholder="Photo" name="user_photo" style="display: none;">
                        <div class="mt-3">
                            <h4>{{ user.us_name }}</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <!-- Full data -->
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <label for="user_name">{{ translate('Name') }}</label>
                        </div>
                        <div class="col-sm-9">
                            <input type="text" class="form-control form-control-rounded" id="user_name" placeholder="{{ user.us_name }}" name="user_name" value="{{ user.us_name }}">
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <label for="user_email">{{ translate('Email') }}</label>
                        </div>
                        <div class="col-sm-9">
                            <input type="email" class="form-control form-control-rounded" id="us_email" placeholder="{{ user.us_email }}" name="user_email" value="{{ user.us_email }}" readonly>
                        </div>
                    </div>  
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <label for="user_birthday">{{ translate('Birthday') }}</label>
                        </div>
                        <div class="col-sm-9">
                            <input type="date" class="form-control form-control-rounded" id="user_birthday" placeholder="{{ user.us_birthday }}" name="user_birthday" value="{{ user.us_birthday }}">
                        </div>
                    </div> 
                    {% if user.us_is_admin or user.us_is_superuser %}
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <label for="user_active">{{ translate('Active') }}</label>
                            </div>
                            <div class="col-sm-3 icheck-material-white">
                                <input type="checkbox" id="user_active" name="user_active" {% if user.us_is_active %}checked{% endif %}>
                                <label for="user_active"></label>
                            </div>
                        </div>
                        <div class="row" style="display: none;">
                            <div class="col-sm-3">
                                <label for="user_buyer">{{ translate('Buyer') }}</label>
                            </div>
                            <div class="col-sm-3 icheck-material-white">
                                <input type="checkbox" id="user_buyer" name="user_buyer" {% if user.us_is_buyer %}checked{% endif %}>
                                <label for="user_buyer"></label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <label for="user_buyer2">{{ translate('Buyer') }}</label>
                            </div>
                            <div class="col-sm-3 icheck-material-white">
                                <input type="checkbox" id="user_buyer2" name="user_buyer2" {% if user.us_is_buyer %}checked{% endif %} disabled>
                                <label for="user_buyer2"></label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <label for="user_seller">{{ translate('Seller') }}</label>
                            </div>
                            <div class="col-sm-3 icheck-material-white">
                                <input type="checkbox" id="user_seller" name="user_seller" {% if user.us_is_seller %}checked{% endif %}>
                                <label for="user_seller"></label>
                            </div>
                        </div>
                        <div class="row"  style="display: none;">
                            <div class="col-sm-3">
                                <label for="user_admin">{{ translate('Admin') }}</label>
                            </div>
                            <div class="col-sm-3 icheck-material-white">
                                <input type="checkbox" id="user_admin" name="user_admin" {% if user.us_is_admin %}checked{% endif %}>
                                <label for="user_admin"></label>
                            </div>
                        </div>
                        <div class="row"  style="display: none;">
                            <div class="col-sm-3">
                                <label for="user_superuser">{{ translate('SuperUser') }}</label>
                            </div>
                            <div class="col-sm-3 icheck-material-white">
                                <input type="checkbox" id="user_superuser" name="user_superuser" {% if user.us_is_superuser %}checked{% endif %}>
                                <label for="user_superuser"></label>
                            </div>
                        </div>
                    {% else %}
                        <div style="display: none;">
                            <input type="checkbox" id="user_active" name="user_active" {% if user.us_is_active %}checked{% endif %}>
                            <input type="checkbox" id="user_buyer" name="user_buyer" {% if user.us_is_buyer %}checked{% endif %}>
                            <input type="checkbox" id="user_seller" name="user_seller" {% if user.us_is_seller %}checked{% endif %}>
                            <input type="checkbox" id="user_admin" name="user_admin" {% if user.us_is_admin %}checked{% endif %}>
                            <input type="checkbox" id="user_superuser" name="user_superuser" {% if user.us_is_superuser %}checked{% endif %}>
                        </div>
                    {% endif %}
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <button type="submit" class="btn btn-light btn-round px-3"><i class="icon-save"></i> {{ translate('Edit User') }}</button>
                            </div>
                        </div>
                        {% if not user.us_is_seller and not user.us_is_superuser %}
                        <div class="form-group">
                            <button type="submit" formaction="{{ url_for('views.request_seller') }}" formmethod="post" class="btn btn-secondary btn-round px-3"> {{ translate('Become a Seller') }}</button>
                        </div>                       
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!--END ROW -->


<!-- Chart js -->
<script src="../static/plugins/Chart.js/Chart.min.js"></script>
<!-- Index js -->
<script src="../static/js/index.js"></script>
<script>
    document.getElementById('user_photo_img').addEventListener('click', function() {
        document.getElementById('user_photo').click();
    });
</script>
{% endblock %}